import type { Metadata } from "next";

import Link from "next/link";
import { Brush, FileCode, Globe, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "工具",
  description: "Generated by create next app",
};
interface TheoProject {
  name: string;
  tag: string;
  url: string;
  icon: React.ReactNode;
}

const TheoProjects: TheoProject[] = [{
  name:"网页生成",
  tag:"HTML",
  url:"/Theo",
  icon:<FileCode size={20} className="text-blue-500" />
},{
  name:"Seo建议",
  url:"/Theo/Seo",
  tag:"SEO",
  icon:<Globe size={20} className="text-green-500" />
},{
  name:"AI绘画",
  url:"/Theo/Cover",
  tag:"AI",
  icon:<Brush size={20} className="text-purple-500" />
}]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex overflow-hidden min-h-screen">
      <aside className="w-16 md:w-72 lg:w-80 transition-all duration-300 ease-in-out border-r border-gray-200 dark:border-gray-800 flex flex-col h-screen sticky top-0  backdrop-blur-sm shadow-lg z-10">
        <div className="p-6 border-b border-gray-200 dark:border-gray-800">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-indigo-500 animate-pulse" />
            <span className="hidden md:inline">工具列表</span>
          </h3>
        </div>
        <nav className="flex-1 overflow-y-auto py-6 px-2 md:px-4">
          <div className="space-y-3">
            <TooltipProvider delayDuration={200}>
              {TheoProjects.map((project) => (
                <Tooltip key={project.name}>
                  <TooltipTrigger className="w-full" asChild>
                    <Link href={project.url}>
                      <div 
                        className={cn(
                          "group flex items-center px-3 py-3 text-sm rounded-xl gap-3",
                          "transition-all duration-300 ease-out",
                          "text-gray-700 dark:text-gray-300",
                          "hover:bg-gradient-to-r hover:from-gray-50 hover:to-indigo-50", 
                          "dark:hover:bg-gradient-to-r dark:hover:from-gray-800/40 dark:hover:to-indigo-900/20",
                          "border-l-[3px] border-transparent hover:border-l-indigo-500",
                          "transform hover:translate-x-1 hover:shadow-sm"
                        )}
                      >
                        <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-gray-100 dark:bg-gray-800 group-hover:bg-white dark:group-hover:bg-gray-700 transition-colors duration-300 shadow-sm">
                          {project.icon}
                        </div>
                        <span className="font-medium group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-all duration-300 hidden md:block">
                          {project.name}
                        </span>
                        <span className="ml-auto text-xs px-2.5 py-1 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 group-hover:bg-white group-hover:text-indigo-600 dark:group-hover:bg-gray-700 dark:group-hover:text-indigo-400 transition-all duration-300 hidden md:block">
                          {project.tag}
                        </span>
                      </div>
                    </Link>
                  </TooltipTrigger>
                  <TooltipContent 
                    side="right" 
                    className="text-xs bg-gray-900 text-gray-100 dark:bg-gray-800 dark:text-white px-3 py-2 rounded-md shadow-xl"
                  >
                    {project.name} - {project.tag}
                  </TooltipContent>
                </Tooltip>
              ))}
            </TooltipProvider>
          </div>
        </nav>
      </aside>
      <main className="flex-1 p-4 md:p-8 overflow-y-auto bg-gray-50 dark:bg-gray-900/30">
        {children}
      </main>
    </div>
  );
}
