import type { Metadata } from "next";

import Link from "next/link";
import { DramaIcon, Section, Webcam } from "lucide-react";
import { cn } from "@/lib/utils";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "工具",
  description: "Generated by create next app",
};
interface TheoProject {
  name: string;
  tag: string;
  url: string;
  icon: React.ReactNode;
}

const TheoProjects: TheoProject[] = [{
  name:"网页生成",
  tag:"HTML",
  url:"/Theo",
  icon:<Webcam size={20} ></Webcam>
},{
name:"Seo建议",
url:"/Theo/Seo",
tag:"SEO",
icon:<Section size={20} ></Section>
},{
name:"AI绘画",
url:"/Theo/Cover",
tag:"AI",
icon:<DramaIcon size={20}  ></DramaIcon>
}]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex overflow-hidden min-h-screen bg-gray-50 dark:bg-gray-900">
      <aside className="w-56 border-r border-gray-200 dark:border-gray-800 flex flex-col h-screen sticky top-0 bg-white dark:bg-gray-950 shadow-sm">
        <div className="p-4 border-b border-gray-200 dark:border-gray-800">
          <h3 className="text-sm font-medium text-gray-900 dark:text-gray-100">工具列表</h3>
        </div>
        <nav className="flex-1 overflow-y-auto py-4 px-3">
          <div className="space-y-1">
            <TooltipProvider>
              {TheoProjects.map((project) => (
                <Tooltip key={project.name}>
                  <TooltipTrigger asChild>
                    <Link href={project.url}>
                      <div 
                        className={cn(
                          "group flex items-center px-3 py-2 text-sm rounded-md gap-3",
                          "transition-colors duration-150 ease-in-out",
                          "text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800",
                          "border-l-2 border-transparent hover:border-l-2 hover:border-l-indigo-500"
                        )}
                      >
                        <span className="text-gray-500 group-hover:text-indigo-600 dark:text-gray-400 dark:group-hover:text-indigo-400 transition-colors duration-150">
                          {project.icon}
                        </span>
                        <span className="font-medium">{project.name}</span>
                        <span className="ml-auto text-xs px-2 py-0.5 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400">
                          {project.tag}
                        </span>
                      </div>
                    </Link>
                  </TooltipTrigger>
                  <TooltipContent side="right" className="text-xs">
                    {project.name} - {project.tag}
                  </TooltipContent>
                </Tooltip>
              ))}
            </TooltipProvider>
          </div>
        </nav>
      </aside>
      <main className="flex-1 p-6 overflow-y-auto">
        {children}
      </main>
    </div>
  );
}
