import type { Metadata } from "next";
import {BoxProvider} from "@/contexts/box-context";
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from "@/components/ui/resizable";
import { Sidebar, SidebarContent, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { DramaIcon, Section, Webcam } from "lucide-react";

export const metadata: Metadata = {
  title: "工具",
  description: "Generated by create next app",
};
const TheoProjects:TheoProject[]=[{
  name:"网页生成",
  tag:"HTML",
  url:"/Theo",
  icon:<Webcam size={20} ></Webcam>
},{
name:"Seo建议",
url:"/Theo/Seo",
tag:"SEO",
icon:<Section size={20} ></Section>
},{
name:"AI绘画",
url:"/Theo/Cover",
tag:"AI",
icon:<DramaIcon size={20}  ></DramaIcon>
}]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="flex overflow-hidden p-2  ">
    <div className=" w-32 h-full p-2 border-r border-red-300 ">
       {
        TheoProjects.map(e=>{
           return <Link  key={e.name} href={e.url}>
            <div className="text-sm hover:bg-black/5 p-2 rounded-md gap-2 my-2 text-nowrap flex "  
           
           ><span>{e.icon}</span>{e.name}</div></Link>
        })
       }
    </div>
    <div className="w-full h-full">
      {children}
    </div>
  </div>
  

}
