import type { Metadata } from "next";
import Header from '@/components/Header'
import SessionWrapper from '@/components/SessionWrapper';
import {  Ma_Shan_Zheng as MA  } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import { QueryClientProvider } from '../lib/QueryClientProvider';
import {CardProvider} from '@/contexts/card-context'
import {ViewTransitions} from 'next-view-transitions'
import "./globals.css";
import { motion } from "framer-motion";
import SplashCursor from "@/components/home/SplashCursor";
import { Github, Twitter, X } from "lucide-react";


// 1. 配置主字体
const inter =MA({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: "400"
})




export const metadata: Metadata = {
  title: "webcard-share",
  description: "Generated by create next app",
  alternates: {
    canonical: 'https://yourdomain.com',
    types: {
      'application/rss+xml': [{ url: 'feed.xml', title: 'RSS 订阅' }],
    },
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  
  return ( 
    <CardProvider >
    <SessionWrapper>
      <ViewTransitions>
       
        <html lang="en" className={`${inter.variable}`}  >
       
          <body className="bg-[#f8f9fa] font-wenkai  dark:bg-black flex flex-col">
            <Header></Header> 
            <main className="flex-2    w-full pt-14  min-h-screen">
              <Toaster></Toaster>     
              <QueryClientProvider>
                {children}
              </QueryClientProvider>
              {modal}
              <div id="modal-root"></div>
            </main>
            <footer className="flex flex-col items-center justify-center p-2 gap-2 w-full ">
              欢迎联系我
            <div className="flex justify-center p-2 gap-4 w-full ">
            <a href="https://x.com/QIN_KING88"><Twitter ></Twitter></a>
              <div>微信号:wx2580456922</div>
              <a href="https://github.com/Theoool/"><Github ></Github></a>
            </div>
             <span className="flex gap-2">开源地址：<a href="https://github.com/Theoool/webcard-share"><Github ></Github></a>
             项目非常不成熟，欢迎提issue,我们一起构建，一起成长！浏览器插件正在开发中
             </span>
               </footer>
          </body>
        </html>
       
     
      </ViewTransitions>
    </SessionWrapper>
    </CardProvider>
  );
}
