import type { Metadata } from "next";
import Header from '@/components/Header'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import {  Ma_Shan_Zheng as MA  } from "next/font/google";

import "./globals.css";



// 1. 配置主字体
const inter =MA({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: "400"
})


export const metadata: Metadata = {
  title: "webcard-share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    <html lang="en"  className={`${inter.variable}`}>
   <body >
  
   <SidebarProvider className="flex w-full">

      <AppSidebar />
      <main  className="flex-1 px-2 py-3  min-h-screen">
     
        <Header></Header>
        <SidebarTrigger  className=" fixed center "/>  
        {children}
      </main>
      
    </SidebarProvider>
   </body>
    </html>
  );
}
