import type { Metadata } from "next";
import {BoxProvider} from "@/contexts/box-context";

export const metadata: Metadata = {
  title: "webcard-share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <BoxProvider>
  <div>
        {children}
     </div>
     </BoxProvider>
  
}
